### ISSUE TITLE
Creating a local folder structure similar to the relative path in "LocalPath" in database.xml in custom Repositories allows Relative Path Hijacking

### ISSUE THREAD

**Issue by mariusbfjeld** [jantari/LSUClient#122]
### Version

1.7.0

### Computer Model

All

### Problem

We use LSUClient along with Lenovo Update Retriever to curate a local self-hosted repository, and a pentest found the following
- If you know the ID of a driver that's going to be installed, you can create the relative path structure from the xml locally on the client. Some part of `Get-PackagesInRepository` or `Get-PackagePathInfo` finds this local path and uses it instead of the path to the driver on the repository.
- This opens a security risk where a malicious user can create the xml and folder structure, put the installer path in the xml to be a given hack or malware, then when the package runs with administrative privileges, the malware is executed.

I have tried to resolve it myself by adding `"C:\ProgramData\LSUPackages"` prepended to the XML Local Path variable in database.xml, but this means that `Get-PackagesInRepository` can't find the driver, as it doesn't exists locally on the client yet.
If I then get `Get-PackagesInRepository` to ignore my prepended path, it finds the driver in the repository, but also the local malware structure I create.

I apologise if this is unclear, but I've been wracking my brains trying to find exactly where this happens in the module, but I'm at a loss. 
I guess my point is, from a security standpoint, `Get-LSUpdate` should not be looking locally on the client to complete the relative path, unless implicitly instructed to. If I supply a `-Repository` to `Get-LSUpdate`, the return values for drivers and paths should only ever be from the `-Repository`.

**Comment by jantari** [comment]
Thanks for the report. I think I understand, but would like some additional details to be able to reproduce it.

Can you confirm:

1. You are sourcing packages from a `database.xml`-type repository created with Lenovo Update Retriever
2. The `LocalPath`s in the XML file are relative paths, not fully qualified

And also provide this info:

1. How are you serving this repository to the clients running LSUClient? Is the repository in a locally accessible filesystem like the OS drive, a USB drive etc. or on a network share or served via a webserver
2. Can you give me the path you are passing to `-Repository` parameter, an example `LocalPath` from the XML and the full path where you are able to put potentially malicious files that LSUClient then picks up? I want to see how all these paths are related / where they are similar.
3. If it's possible, please provide the output of `Get-LSUpdate -Verbose -Debug` when running against your repository - you can also create a copy of the repository with only one package just to reproduce this issue, it would make the output much shorter
4. After retrieving packages from your repository with `Get-LSUpdate` or `Get-LSUpdate -All`, can you please check the output of the `URL` and `Files` properties of the updates and share where they point to? Is it already the hijacked location being shown at this point? The `Files` property is hidden you have to use `| Format-List URL, Files -Force` or access it directly with `$object.Files` to retrieve it

**Comment by mariusbfjeld** [comment]
Hello!

1. Yes, that is correct. I am getting the updates by running `Get-LSUpdate -Repository <SharePath>`. This works as intended
2. `LocalPath` in `database.xml` are relative paths, this seems to be the crux of the issue.

I have to obfuscate domain name, but hopefully this is still understandable
1. The repository is being served as a network share, accessible via the computer account (script is running as NT Authority\SYSTEM)
2. I run this command `Get-LSUpdate -Repository "\\O-CMDRV-1.domainname\UpdateRetriever"`
  - here's an example from package ID n40ta05w - `<LocalPath>\n40ta05w\n40ta05w_2_.xml</LocalPath>`
  - I can create `C:\n40ta05w\n40ta05w_2_.xml` locally on the client, and Get-LSUpdate outputs an error showing that it was unable to get any information from the xml (this is because I just made a blank xml as proof that it would be found)
3.  I work in a secure environment, so I would prefer not to, unless it is still necessary after the other information here is provided.



4. If there is no folder structure locally on the client that mirrors the `LocalPath` for the package in `database.xml`, then URL points to `\\O-CMDRV-1.domainname\UpdateRetriever\n40ta05w\n40ta05w_2_.xml` and Files are just the three files in that folder on the repo.
5. However, if I were to copy the `n40ta05w\n40ta05w_2_.xml` structure and file to my local client, change the Installer value from `<Name>n40ta05w.exe</Name` to `<Name>RandomHack.Exe</Name>` and put `RandomHack.exe` in the same folder locally on the client, `Install-LSUpdate` will run this installer, as it found the package and structure locally on the client first through the relative path from `database.xml`. 

Does this make it more clear? I work in a secure environment so testing and sharing data is a bit finicky, but I will do my best.

**Comment by jantari** [comment]
Thanks for the additional details. I was able to reproduce the issue and find the root cause.

Technically, the behavior of LSUClient is perfectly correct. A file path beginning with a single leading backslash such as `\n40ta05w\n40ta05w_2_.xml` is relative to the root of the current drive (e.g. `C:`) and NOT to the current directory. See: https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#fully-qualified-vs-relative-paths

If these were manually created or edited XML files I would simply consider this a user error: you just have to put the LocalPath in correctly, if it's supposed to be relative to the repository it would have to be `.\n40ta05w\n40ta05w_2_.xml` or just `n40ta05w\n40ta05w_2_.xml`. But because Update Retriever produces these wrong file paths, and quite a few people use Update Retriever, I have to implement a fix on my end.

I will keep you updated.

**Comment by jantari** [comment]
I have pushed a change to the [develop branch](https://github.com/jantari/LSUClient/tree/develop) that addresses this. If you can, please download the module from the develop-branch and try with that version to validate your issue is fixed.

If you can confirm it works I am happy to release these changes soon as a v1.8.0.

It will be a breaking change because paths like `\n40ta05w\n40ta05w_2_.xml` (and `C:n40ta05w\n40ta05w_2_.xml`, and `~\n40ta05w\n40ta05w_2_.xml`) will no longer be resolved _correctly_ (as Windows would do it), but sometimes less is more when features end up causing confusion or security concerns such as in this case - and I doubt many people, if any, are intentionally putting unusual path specifications like these into their self-hosted repositories' XMLs. Hopefully.

**Comment by mariusbfjeld** [comment]
Looks great at a cursory glance! I will get it tested and report back shortly :)

**Comment by mariusbfjeld** [comment]
Hello again! I've tried now, and it seems `Get-LSUpdate` is unable to recognise the repository now, somehow. I've verified that database.xml is existing and formatted correctly, nothing else has changed on my part. If I run the same command from version 1.7.0, I get the expected output.

Here is the verbose output from `Get-LSUpdate -Repository "\\O-CMDRV-1.dom.ain.name\UpdateRetriever"`, I've only obfuscated the domain part of the FQDN

```
PS C:\WINDOWS\system32> Get-LSUpdate -Repository "\\O-CMDRV-1.dom.ain.name\UpdateRetriever" -Verbose
VERBOSE: Lenovo Model is: 20Y3
VERBOSE: Created temporary scratch directory: C:\WINDOWS\TEMP\n3ezlj3r.nha
VERBOSE: Looking for packages in repository '\\O-CMDRV-1.dom.ain.name\UpdateRetriever' (Type: FILE)
WARNING: The repository '\\O-CMDRV-1.dom.ain.name\UpdateRetriever' did not contain either a '20Y3_Win11.xml' or
'database.xml' file to get packages from
WARNING: Could not get 20Y3_Win11.xml: '\\O-CMDRV-1.dom.ain.name\UpdateRetriever\20Y3_Win11.xml' is not a supported
URL and does not exist as a filesystem path
WARNING: Could not get database.xml: '\\O-CMDRV-1.dom.ain.name\UpdateRetriever\database.xml' is not a supported URL
and does not exist as a filesystem path
No packages for computer model '20Y3' could be retrieved from repository '\\O-CMDRV-1.dom.ain.name\UpdateRetriever'
At C:\Users\Administrator\Desktop\LSUClient-develop\LSUClient-develop\public\Get-LSUpdate.ps1:159 char:13
+             throw "No packages for computer model '${Model}' could be ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (No packages for...pdateRetriever':String) [], RuntimeException
    + FullyQualifiedErrorId : No packages for computer model '20Y3' could be retrieved from repository '\\O-CMDRV-1.dom.ain.name\UpdateRetriever'
```

**Comment by jantari** [comment]
My bad, fixed in 5609f5c - please try again with the latest changes

**Comment by mariusbfjeld** [comment]
Hello! I downloaded the "develop" branch after your latest commits, but I still get the same issue. I have verified with `Test-Path "\\O-CMDRV-1.dom.ain.name\UpdateRetriever\database.xml"` that I am able to reach the database file. 
The output from `Get-LSUpdate -Repository "\\O-CMDRV-1.dom.ain.name\UpdateRetriever"` is identical to my previous comment. 

Is there anything you want me to test or verify on my end?

**Comment by jantari** [comment]
I can't see how you could still get that error, so I added some additional Write-Debug statements for you to help understand what is happening. Please download the latest develop version again and retry with that, thank you for your help

**Comment by mariusbfjeld** [comment]
It works now! I'm not sure if it was a me-problem or one of the fixes you did, but I get the proper output from Get-LSUpdate now. 

When I run `Get-LSUpdate -Repository "\\O-CMDRV-1.dom.ain.name\UpdateRetriever"`, select the first driver in the list, replicate the folder structure to `C:\n40ta05w` and put the XML in there similar to earlier test, then re-run `Get-LSUpdate`, checking the contents of URL and Files points to my repository and not locally on the client.

Everything seems to be working as it should now. Thank you!

**Comment by mariusbfjeld** [comment]
Do you have any idea on roughly when this will be in a new release?

**Comment by jantari** [comment]
Hopefully this week, I have unfortunately not had much time recently.

**Comment by jantari** [comment]
It's out. Writing up the documentation on the change is what took the most time.
